name: Run Automated Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout todolist APP
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4

      - name: Install Deps
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Checkout test repo
        run: git clone https://github.com/pipeolis/topicos-avanzados-taller-cuatro.git

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install tests deps
        run: |
          cd topicos-avanzados-taller-cuatro
          npm ci

      - name: Install Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --config=topicos-avanzados-taller-cuatro/playwright.config.ts
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
           name: playwright-report
           path: topicos-avanzados-taller-cuatro/playwright-report/
           retention-days: 1
